before_install:
  - sudo apt-get update

install:
  - sudo apt-get install -y gdnsd

before_script:
  - sudo cp config /etc/gdnsd/
  - sudo cp zones/* /etc/gdnsd/zones/

script:
  - sudo gdnsd checkconf

notifications:
  irc:
    channels:
      - "chat.freenode.net#miraheze"
    on_success: change
    on_failure: always
    skip_join: false
    template:
      - "%{repository}/%{branch}/%{commit} - %{author} 
%{message} %{build_url}"
  email:
    recipients:
      - john@miraheze.org
    on_success: change
    on_failure: always
