sudo: required
dist: trusty


install:
  - sudo apt-get install -y --force-yes gdnsd

before_script:
  - sudo cp config /etc/gdnsd/
  - sudo cp admin_state /etc/gdnsd/
  - sudo cp zones/* /etc/gdnsd/zones/

script:
  - sudo gdnsd checkconf

notifications:
  irc:
    channels:
      - "chat.freenode.net#miraheze"
    on_success: change
    on_failure: always
    skip_join: true
    template:
      - "%{repository}/%{branch}/%{commit} - %{author} 
%{message} %{build_url}"
  email:
    recipients:
      - southparkfan@miraheze.org
    on_success: change
    on_failure: always
