sudo: required
dist: xenial


install:
  - sudo apt-get install -y --force-yes gdnsd

before_script:
  - sudo curl http://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz --output ~/GeoLite2-Country.tar.gz
  - cd ~
  - gunzip ~/GeoLite2-Country.tar.gz
  - tar -xvf ~/GeoLite2-Country.tar
  - sudo mkdir -p /usr/share/GeoIP
  - ls -lah ~/GeoLite2-Country_*/
  - sudo cp ~/GeoLite2-Country_*/GeoLite2-Country.mmdb /usr/share/GeoIP/GeoLite2-Country.mmdb
  - sudo cp config /etc/gdnsd/
  - sudo cp admin_state /etc/gdnsd/
  - sudo cp zones/* /etc/gdnsd/zones/

script:
  - sudo gdnsd checkconf

notifications:
  irc:
    channels:
      - "chat.freenode.net#miraheze"
    on_success: change
    on_failure: always
    template:
      - "%{repository}/%{branch}/%{commit} - %{author} 
%{message} %{build_url}"
  email:
    recipients:
      - southparkfan@miraheze.org
    on_success: change
    on_failure: always
